[platformio]
description = oled + wifi + websocket
default_envs = esp32dev

[env]
build_flags = -Wno-deprecated-declarations
monitor_speed = 115200
framework = arduino
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    https://github.com/nhatuan84/esp32-sh1106-oled
    links2004/WebSockets @ ^2.3.6        ; WebSocketsClient used directly (no SocketIO wrapper)
    bblanchon/ArduinoJson @ ^7.4.1
    sui77/rc-switch @ ^2.6.4



[env:esp32dev]
platform = espressif32
board = esp32dev
monitor_speed = 115200
upload_speed = 921600
